export type PersonWithOptionalAlternateName<P extends PersonName> =
	| P
	| PersonWithAlternateName<P>;

export type PersonWithOptionalRole<P extends PersonName> =
	| P
	| PersonWithRole<P>;

export interface PersonWithAlternateName<P extends PersonName> {
	readonly name: P;
	readonly alternateName: string;
}

export interface PersonWithQuirk<P extends PersonName> {
	readonly name: P;
	readonly quirk: string;
}

export interface PersonWithRole<P extends PersonName> {
	readonly name: P;
	readonly role: string;
}

export type PersonName =
	| "Adam Rippon"
	| "Adelaide Kane"
	| "Adrienne Houghton"
	| "Aisha Tyler"
	| "Alfonso Ribeiro"
	| "Amber Riley"
	| "Andrea Navedo"
	| "Anna Wanselius"
	| "Anne King"
	| "Archie Hahn"
	| "Ardal O'Hanlon"
	| "Arthur Smith"
	| "Ava Fabian"
	| "Betty Thomas"
	| "Bill Nye"
	| "Bob Derkach"
	| "Brad Sherwood"
	| "Brett Dier"
	| "Brian Shaw"
	| "Bridie Connell"
	| "Cal Wilson"
	| "Candice Accola"
	| "Candice Patton"
	| "Candy Girard"
	| "Carmen Electra"
	| "Caroline Quentin"
	| "Carson Kressley"
	| "Catherine O'Hara"
	| "Cece Worrall-Rubin"
	| "Cedric the Entertainer"
	| "Charlie Sheen"
	| "Cheryl Hines"
	| "Chip Esten"
	| "Chloe Butler and Monique Gaxiola"
	| "Chris De'Sean Lee"
	| "Chris Hardwick"
	| "Chris Jackson"
	| "Chris Jericho"
	| "Chris Langham"
	| "Christopher Smith"
	| "Clive Anderson"
	| "Colin Mochrie"
	| "Cornelius Smith Jr."
	| "Danielle Panabaker"
	| "Darren Criss"
	| "David Hasselhoff"
	| "Debi Durst"
	| "Debra Wilson"
	| "Denalda Williams"
	| "Denny Siegel"
	| "Drew Carey"
	| "Eddie Izzard"
	| "Elizabeth Gillies"
	| "Emily Bett Rickards"
	| "Enn Reitel"
	| "Florence Henderson"
	| "Fourplay with Judy"
	| "Gary Anthony Williams"
	| "George McGrath"
	| "George Wendt"
	| "Gina Rodriguez"
	| "Grace Byers"
	| "Graeme Garden"
	| "Greg Proops"
	| "Griff Rhys Jones"
	| "Gwendolyn Osborne"
	| "Heather Anne Campbell"
	| "Heather Morris"
	| "Hugh Hefner"
	| "Ian Gomez"
	| "Jack Osbourne"
	| "Jaime Camil"
	| "Jan Ravens"
	| "Jane Brucker"
	| "Jayne Trcka"
	| "Jeanine Mason"
	| "Jeff Davis"
	| "Jerry Springer"
	| "Jillian Michaels"
	| "Jim Meskimen"
	| "Jim Sweeney"
	| "Jimmy Mulville"
	| "Joanie Laurer"
	| "Joey Fatone"
	| "John Sessions"
	| "Jon Glover"
	| "Jonathan Mangum"
	| "Jonathan Pryce"
	| "Josie Lawrence"
	| "Julian Clary"
	| "Julie Larson"
	| "Kaitlin Doubleday"
	| "Karen Maruyama"
	| "Karla Souza"
	| "Kat Graham"
	| "Kathie Lee Gifford"
	| "Kathy Greenwood"
	| "Kathy Griffin"
	| "Kathy Kinney"
	| "Katie Cassidy"
	| "Katie Harman"
	| "Kearran Giovanni"
	| "Keegan-Michael Key"
	| "Kevin McHale"
	| "Kunal Nayyar"
	| "Kyle Richards"
	| "Laila Ali"
	| "Lance Bass"
	| "Lassie"
	| "Laura Hall"
	| "Lauren Cohan"
	| "Lea Thompson"
	| "Lee Simpson"
	| "Linda Taylor"
	| "Lisa Leslie"
	| "Lolo Jones"
	| "Loyola Marymount University cheerleaders"
	| "Lyndie Greenwood"
	| "Maggie Q"
	| "Malcolm Goodwin"
	| "Manuela Arbeláez"
	| "Marisol Nichols"
	| "Mark Cohen"
	| "Matt Barnes"
	| "Mel B"
	| "Michael Weatherly"
	| "Mike McShane"
	| "Mircea Monroe"
	| "Misha Collins"
	| "Misty May-Treanor"
	| "Neena and Veena Bidasha"
	| "Neil Mullarkey"
	| "Niall Ashdown"
	| "Nina Agdal"
	| "Nolan Gould"
	| "Nyima Funk"
	| "Padma Lakshmi"
	| "Patrick Bristow"
	| "Paul Merton"
	| "Paul Rider"
	| "Penn & Teller"
	| "Peter Cook"
	| "Phil LaMarr"
	| "Rachel Bloom"
	| "Rachel Reynolds"
	| "Ralph Macchio"
	| "Randy Couture"
	| "Rhys Darby"
	| "Rich Fields"
	| "Richard Kaplan"
	| "Richard Simmons"
	| "Richard Vranch"
	| "Ricki Lake"
	| "Rob Gronkowski"
	| "Robbie Amell"
	| "Robin Williams"
	| "Ron West"
	| "Rory Bremner"
	| "Rory McGrath"
	| "Ross Mathews"
	| "Russell Fletcher"
	| "Ryan Stiles"
	| "Sam Johnson"
	| "Sandi Toksvig"
	| "Santa Claus and Donner"
	| "Scott Porter"
	| "Sean Masterson"
	| "Shawn Johnson"
	| "Sheryl Underwood"
	| "Sid Caesar"
	| "Steen Raskopoulos"
	| "Stephen Colbert"
	| "Stephen Frost"
	| "Stephen Fry"
	| "Steve Kamer"
	| "Steve Steen"
	| "Susie Youssef"
	| "Tamera Mowry"
	| "Tara Lipinski"
	| "Tegan Higginbotham"
	| "The Bella Twins"
	| "Tinashe"
	| "Tom Walker"
	| "Tommy Little"
	| "Tony Cavalero"
	| "Tony Hawk"
	| "Tony Slattery"
	| "US Olympic Synchronized Swimming Team"
	| "Ulambayaryn Byambajav"
	| "Undarma Darihu"
	| "Verne Troyer"
	| "Vernon Davis"
	| "Victoria Fuller"
	| "Wanya Morris"
	| "Wayne Brady"
	| "Wendi McLendon-Covey"
	| "Whoopi Goldberg"
	| "Wil Wheaton"
	| "Willie Robertson"
	| "Wilson Bethel"
	| "Win Meyerson"
	| "Yvette Nicole Brown";
